ALTER TYPE "ConnectorProvider" ADD VALUE IF NOT EXISTS 'RIPPLING';
ALTER TYPE "DataSource" ADD VALUE IF NOT EXISTS 'RIPPLING';

ALTER TABLE "Person" ADD COLUMN IF NOT EXISTS "holidayAllowanceDays" DOUBLE PRECISION;
ALTER TABLE "Person" ADD COLUMN IF NOT EXISTS "holidayRemainingDays" DOUBLE PRECISION;
ALTER TABLE "Person" ADD COLUMN IF NOT EXISTS "costCentre" TEXT;
ALTER TABLE "Person" ADD COLUMN IF NOT EXISTS "workingPattern" TEXT;
ALTER TABLE "Person" ADD COLUMN IF NOT EXISTS "ftePercent" INTEGER NOT NULL DEFAULT 100;
ALTER TABLE "Person" ADD COLUMN IF NOT EXISTS "nextReviewDate" TIMESTAMP(3);
ALTER TABLE "Person" ADD COLUMN IF NOT EXISTS "probationEndDate" TIMESTAMP(3);
ALTER TABLE "Person" ADD COLUMN IF NOT EXISTS "contractEndDate" TIMESTAMP(3);
ALTER TABLE "Person" ADD COLUMN IF NOT EXISTS "noticePeriodDays" INTEGER;
